#ifndef SM4SDK_VMNSocialMediaRequestCodes_h
#define SM4SDK_VMNSocialMediaRequestCodes_h

#define UNKNOWN  0
#define OK 1
#define NOTLOGGEDIN 2
#define ACCOUTNOTFOUND 3
#define INVALIDPARAMETERS 4
#define BLOCKED 5
#define ACCOUNTBANNED 6
#define CANTFRIENDYOURSELF 7

#define INCORRECTCAPTCHA 8
#define CONTENTNOTFOUND 9
#define SYSTEMERROR 10
#define INVALIDPASSWORD 11
#define ERROR 12
#define RATINGILLEGAL 13
#define RATINGUNSUPPORTEDSYSTEM 14
#define FORBIDDEN 15
#define FACEBOOKACCOUNTALREADYLINKEDTOANOTHER 16
#define FACEBOOKLOGINCOMPLETE 17
#define FACEBOOKSIGNUPCOMPLETE 18

#define REQUIREDFIELDISNOTSPECIFIED 19
#define NONFLUXCONTENT 20

#define USERISALREADYGROUPMEMBER 21
#define WRONGSERVERAPIKEY 22
#define CONTENTWRONGOWNER 23
#define CONTENTALREADYDELETED 24
#define COMMENTNOTFOUND 25
#define INVALIDACCESSTOKEN 26
#define FACEBOOKAPILIMIT 27
#define FAILEDFACEBOOKAPI 28
#define FAILEDTWITTERAPI 29
#define TWITTERLOGINCOMPLETE 30

#endif
